# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import risk_extractor_pb2 as risk__extractor__pb2


class RiskExtractorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractRisks = channel.unary_unary(
                '/risk_extractor.RiskExtractor/ExtractRisks',
                request_serializer=risk__extractor__pb2.ExtractRisksRequest.SerializeToString,
                response_deserializer=risk__extractor__pb2.ExtractRisksResponse.FromString,
                )


class RiskExtractorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractRisks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskExtractorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractRisks': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractRisks,
                    request_deserializer=risk__extractor__pb2.ExtractRisksRequest.FromString,
                    response_serializer=risk__extractor__pb2.ExtractRisksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'risk_extractor.RiskExtractor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RiskExtractor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractRisks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risk_extractor.RiskExtractor/ExtractRisks',
            risk__extractor__pb2.ExtractRisksRequest.SerializeToString,
            risk__extractor__pb2.ExtractRisksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
